# Generated by Django 2.2.3 on 2019-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190626_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='video_url',
            field=models.CharField(default='', max_length=256, verbose_name='视频地址'),
        ),
    ]
