# Generated by Django 2.2.3 on 2019-07-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_device_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(default='', max_length=128, verbose_name='微信openID'),
        ),
    ]
