# Generated by Django 2.2.2 on 2019-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_wechat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('open_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
    ]
